### ISSUE TITLE
Min version of Yorick required

### ISSUE THREAD

**Issue by jameshume** [dhmunro/pyorick#1]
Hi,

Sorry for posting here, can't access wiki.

Running 2.2.01 yorick, pyorick doesn run. I compiled 2.0.2.04x and pyorick works like a charm :) What is the minimum version of yorick required to run pyorick?

Ta,
James

**Comment by dhmunro** [comment]
39de730fcd68502136c56ef68d76fce8f3e274d4   of July 9 2014 is the crucial yorick commit.  Obviously it is unwise to back up to old commits.  The y_2_2_04 tag of May 19 2015, corresponding to the first 2.2.04 release, is the earliest tagged version with fd_read and fd_write.  The earliest Debian package which could run pyorick is jesse-backports; pyorick itself is available as a package in that distro.

**Comment by jameshume** [comment]
Thank you.
