### ISSUE TITLE
Comppatibility with Python 3.10: Sequence and Mapping moved to collections.abc

### ISSUE THREAD

**Issue by paumard** [dhmunro/pyorick#3]
Sequence and Mapping where moved from collections to collections.abc in Python 3.3:
https://docs.python.org/3/library/collections.abc.html

It was still possible to import them from collections until 3.9. Now, the import line in pyorick.py needs to be fixed. See attached patch
[collections_abc.txt](https://github.com/LLNL/pyorick/files/7920543/collections_abc.txt)
.

**Comment by dhmunro** [comment]
Finally should be fixed.  Will be broken before Python 3.3.  If broken in 2.7, probably need to fix again.
